name: submission
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  firebase_core: ^4.2.0
  firebase_ml_model_downloader: ^0.4.0+3
  flutter:
    sdk: flutter
  http: ^1.5.0
  image: ^4.5.4
  image_cropper: ^11.0.0
  image_picker: ^1.2.0
  path_provider:
  permission_handler: ^12.0.1
  provider: ^6.1.5+1
  tflite_flutter: ^0.11.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/labels.txt
